OpenBCI/OpenBCI_NodeJS

test/openbci-sdk-test.js
This is a fix to get the travis-ci working every time. The ntp unit test failed to connect intermittently. Since this is simply a test of the dependency and not the module itself, i ignored it for now.
=> Removed auto test dependent on ntp with travis fail

.travis.yml, package.json
This adds support for running node version 6.x.x by upgrading serialport to version 6.
=> Dev serialport upgrade

README.md, changelog.md, openBCIBoard.js, test/openbci-sdk-test.js
Bug in the read me that had a constructor with improper syntax.
=> Fix constructor in readme.md Closes #66

changelog.md, openBCIBoard.js, package.json, test/OpenBCISample-test.js
* Add tests for parsing raw packets
* Removed `got here` log from `.streamStart()`
* Validate stop byte before emitting `rawDataPacket`
=> Validate packets before emitting raw data packets

README.md, changelog.md, openBCIBoard.js, openBCIConstants.js, openBCISample.js, openBCISimulator.js, package.json, test/OpenBCIConstants-test.js, test/OpenBCISample-test.js, test/openBCIBoard-test.js, test/openBCISimulator-test.js
* Add function `.time()` which should be used in time syncing
* Add function `.syncClocksFull()` which should be used for immediate consecutive time syncs
* Synced object can be emitted on `synced` event. Check `valid` property for if the sync was done
* Add detailed description of object returned on `synced` event to README.md
* Changed option named `timeSync` to `sntpTimeSync`
* Removed function called `.sntpNow()` because it was replaced by `.time()`
* Time sync working
* Module could not work with local time
=> Bug time sync

README.md, changelog.md, openBCIBoard.js, openBCIConstants.js, openBCISample.js, package.json, test/OpenBCIConstants-test.js, test/OpenBCISample-test.js
* Add tutorial/sample code for interfacing the module with lab streaming layer.
* Fixed time synced accel to work OpenBCI_32bit_Library release candidate 5 and newer.
In release candidate 5 for the OpenBCI firmware 2.0.0 time sync access packets send the access data in packets % 10 7,8,9 versus 0,1,2 in earlier release candidates.
=> Update time synced accel packets

changelog.md, openBCIBoard.js, test/openBCIBoard-test.js
* Fixed bug where `connected` and `streaming` were not set in constructor
=> Fix constants not set in constructor

README.md, changelog.md, openBCIBoard.js, openBCIConstants.js, openBCISample.js, openBCISimulator.js, test/openBCIBoard-test.js, test/openBCISimulator-test.js
This adjusts the simulator to behave a little more like reality, such that packets are split into pieces when received.
I have verified that all of the failing tests are due to issues that this additional simulation reveals, and not bugs in it.  They should be fixed either in the tests or in the main library.
=>  Simulate packet fragmentation; fixes #100

openBCIBoard.js, openBCISimulator.js
Just a small change intended to ease maintenance.
_options is repurposed to define not only the default options, but also the possible option choices.  For options with multiple choices, they are listed in an array.  The first item of the array will be used for the default.
The code now enforces the choices and provides the default for all options automatically.
=> Automate the interpretation of options and defaults

openBCISimulator.js, test/openBCIBoard-Impedance-test.js, test/openBCIBoard-test.js
This PR enables a subset of tests to be run under simulated fragmentation.
The intent is to catch during testing issues which previously only occurred with a real board.  I have been running this way locally and adding the revealed fixes to my commits.
=> use fragmentation simulation

changelog.md, openBCIBoard.js, test/openBCIBoard-test.js
Resources were not being cleaned up previously.
Although failing is somewhat harsh, this fix makes possible errors more visible.
=> Connection fails if already connected (fixes #93)

.gitignore, README.md, changelog.md, openBCIBoard.js, openBCISimulator.js, package.json, test/OpenBCIConstants-test.js, test/OpenBCISample-test.js, test/bluebirdChecks.js, test/openBCIBoard-Impedance-test.js, test/openBCIBoard-test.js, test/openBCISimulator-test.js, test/timingEventsAsPromises.js
Fixes #92
Notable changes:
- Added a utils test file that tracks `setTimeout()` and `setInterval()` uses that are never `clear`ed.
- Changed `.connected` to `.isConnected()` so that it may be part of the public API
- Paired uses of `.sntpStart` with matching `.sntpStop`
- Raise a few more errors in places where exceptional things happen
- Handled all forms of disconnection and cleaned up state
=> Fix connection-related leaks and inconsistencies

openBCIBoard.js, openBCISample.js, test/OpenBCISample-test.js
For now this is just a failing test for #115.
So far it looks like there are two issues: the first packet is dropped after the fragmented reset response (unless my understanding of sample numbers is faulty), and only the first two packets of the large buffered clump are processed.
I've also noticed while working with the relevant daisy test, that most of the time the board is not detected as being a daisy board, and the whole test is skipped.  I think this is why it usually passes.
=> Fragmented and Buffered Samples (#115)

openBCIBoard.js, openBCIConstants.js, test/OpenBCIConstants-test.js
The `resolve` function of a Promise takes *exactly one* argument.
All further arguments are ignored. Thus, the newChannelSettingsObject
that was being returned by the channelSet Promise was ignored and
the corresponding value in openBCIBoard was always undefined.
Thus, any calls to channel set would actually break the openBCISample
code as the channelSettingsArray contained an `undefined`.
This fixes the bug.
=> Bugfix: channelSet always fails due to bad resolve()

README.md
Contributing should be off of the `development` branch, `SNTP` misspelled,
and a broken link to the `Testing` section.
=> Some fixes to typos in the README

test/openBCIBoard-test.js
Changes the SNTP test to use the sntp library only once.  It is not designed for use in parallel.
=> Refrain from testing sntp in parallel

README.md, changelog.md, examples/getStreamingDaisy/getStreamingDaisy.js, examples/getStreamingDaisy/package.json, openBCIBoard.js, openBCIConstants.js, openBCISample.js, openBCISimulator.js, package.json, test/OpenBCIConstants-test.js, test/OpenBCISample-test.js, test/openBCIBoard-radio-test.js, test/openBCIBoard-test.js, test/openBCISimulator-test.js
* New simulator option `simulatorDaisyModuleCanBeAttached` - Boolean, deafults to true, allows the simulation of the a hot swapped daisy board or simulates a misinformed module.
* New `EventEmitter` - `hardSet` - for when the module detects the board is not configured as the options for the module intended and tries to save itself. i.e. when the `daisy` option is `true` and a soft reset message is parsed and the module determines that a daisy was not detected, the module will emit `hardSet` then send an attach daisy command to recover. Either `error` will be emitted if unable to attach or `ready` will be emitted if success.
* Add example for streaming with `daisy` and `hardSet`.
* `.setInfoForBoardType()` changed to `.overrideInfoForBoardType()` to elevate it's dangerous nature.
* …
=> Fix 16 chan

README.md, examples/labstreaminglayer/handoff.py, examples/labstreaminglayer/index.js, examples/labstreaminglayer/package.json, examples/labstreaminglayer/readme.md, examples/labstreaminglayer/setup.py
I figured it would be good to add an example of working code for streaming through LSL using the NodeJS SDK . This uses a modified version of the NodeJS -> Python technique shown in the other example file. The code is ready to stream as-is, which should make this directory useful for people who would like to just start streaming on LSL right away.
Equivalent code for the ganglion is mostly written using the same technique (though I'm running into the roadblock in [this Ganglion issue](https://github.com/OpenBCI/OpenBCI_NodeJS_Ganglion/issues/23)!) If this looks good to you, I'll post a pull request there once it's done.
=> Lab Streaming Layer example

README.md
from our chat
i encountered this error requiring rebuild and this may happen to any new users who are on the latest node versions > 48
i felt it would be best right under the npm install section in installation.
=> note about serialport node error

README.md, changelog.md, openBCICyton.js, package.json
* Debug bytes was set to always print in processBytes
=> Fix for printing debug output

README.md, changelog.md, openBCICyton.js, package.json, test/openBCICyton-test.js
* Significantly reduce the properties in `this.info` object to only have firmware version and number of missed packets. Code dependent on this.info should switch to using `numberOfChannels()`, and `getBoardType()` and `sampleRate()` for accurate board info!
=> Working on stabalizing daisy

openBCICyton.js
=> BUG: forgot parenthesis on getBoardType() func

changelog.md, examples/getStreaming/getStreaming.js, openBCICyton.js, package.json, test/openBCICyton-test.js
* Calling sdStart and stop would change the writeOutDelay
* Timeout for v1 was set to 10 ms instead of 50 ms.
* Timeout for v2+ was set to 0 ms instead of 10 ms.
=> FIX: Sending channel setting commands might not work
